#' Draw treemap
#'
#' Draw treemap which shows the number and percentage of cells with 0, 1, 2, etc.
#' clone barcodes.
#'
#' @param cell_by_clone_matrix A data.table where each row denotes a cell, a clone barcode,
#' and the number of reads assigned to the clone.
#' @param valid_cells_bcodes A character vector of cell barcodes for droplets
#' deemed real cells.
#' Can be the cell barcodes in cell by gene matrix generated by cellranger's
#' filtered count matrix.
#' @param cell_bcode_col The column in cell_by_clone_matrix denoting the cell's barcode.
#'
#' @return A ggplot object containing the treemap.
#' @export
#'
#' @examples
#' library(data.table)
#'
#' cell_by_clone_matrix <- data.table(
#'     CellBarcode = c("A", "B", "C", "C"),
#'     CloneBarcode = c("AA", "AA", "BB", "CC"),
#'     n_reads = as.integer(c(2, 2, 2, 1))
#' )
#' draw_treemap(
#'     cell_by_clone_matrix = cell_by_clone_matrix,
#'     valid_cells_bcodes = c("A", "B", "C")
#' )
#'
#' @import treemapify
#'
draw_treemap <- function(cell_by_clone_matrix, valid_cells_bcodes,
                         cell_bcode_col = "CellBarcode") {


    n_cells_with_clone_count <- count_clones_per_cells_for_treemap(
        valid_cells_bcodes = valid_cells_bcodes,
        cell_by_clone_matrix = cell_by_clone_matrix,
        cell_bcode_col = cell_bcode_col)

    plt <- ggplot(n_cells_with_clone_count,
                  aes(fill = n_clone_barcode, area = n_cells, label = perc_and_n_cells)) +
        geom_treemap() +
        geom_treemap_text(colour = "black",
                          place = "centre") +
        labs(
            title = "Distribution of Cells by No. of Detected Clone Barcodes",
            subtitle = paste("Of the",
                             prettyNum(length(valid_cells_bcodes), big.mark = ","),
                             "cells, how many have 0, 1, 2, etc. clone barcodes"),
            fill = "No. of clone barcodes found"
        ) +
        theme(legend.position = "bottom") +
        scale_fill_brewer(palette = "Set3")

    return(plt)
}


#' Count number of clones per cells.
#'
#' Internal function to compute the number of clones detected per cell
#' for drawing treemap.
#'
#' @param valid_cells_bcodes A vector of cells barcodes to get the clone
#' assignments for.
#'
#' @param cell_by_clone_matrix A cell-by-clone matrix generated by
#' `generate_cell_clone_barcode_matrix` function.
#'
#' @param cell_bcode_col Name of the column in `cell_by_clone_matrix` that
#' indicates the cell barcode.
#'
#' @return A data.table denoting the number of clones detected per cell.
#'
#' @keywords internal
#'
count_clones_per_cells_for_treemap <- function(valid_cells_bcodes, cell_by_clone_matrix,
                                               cell_bcode_col) {
    n_valid_cells <- length(valid_cells_bcodes)

    # get the clone barcodes for all cells that are deemed valid.
    # for most cases, these are barcodes for cells which cellranger
    # has deemed valid.


    clone_count_per_cell <- count_clones_per_cells(
        cell_by_clone_matrix = cell_by_clone_matrix,
        cell_bcode_col = cell_bcode_col,
        valid_cells_bcodes = valid_cells_bcodes
    )

    # Convert the n_clone_barcode that are > 10 to actually > 10
    clone_count_per_cell_inc_zeros <- copy(clone_count_per_cell)
    clone_count_per_cell_inc_zeros[, n_clone_barcode := ifelse(n_clone_barcode > 10, "> 10", as.character(n_clone_barcode))]

    # we will add in those valid cells which we can't find any clone barcodes for, and
    # assign n_clone_barcode as 0
    valid_cells_without_clones <- setdiff(
        x = valid_cells_bcodes,
        y = unique(cell_by_clone_matrix[[cell_bcode_col]])
    )
    valid_cells_without_clones_dt <- data.table(
        CellBarcode = valid_cells_without_clones,
        n_clone_barcode = rep(0, length(valid_cells_without_clones))
    )
    setnames(valid_cells_without_clones_dt, "CellBarcode", cell_bcode_col)

    # combine everything
    clone_count_per_cell_inc_zeros <- rbind(
        clone_count_per_cell_inc_zeros,
        valid_cells_without_clones_dt
    )

    # set the level for the clone count per cell
    clone_count_per_cell_level <- c(as.character(seq(0, 10)), "> 10")
    clone_count_per_cell_inc_zeros[, n_clone_barcode := factor(n_clone_barcode, levels = clone_count_per_cell_level)]

    # have to actually count the number of cells with 0, 1, 2, .. clone barcodes
    # in order to get percentage that we draw the treemap for
    n_cells_with_clone_count <- clone_count_per_cell_inc_zeros[, .(n_cells = .N), by=n_clone_barcode]
    n_cells_with_clone_count <- n_cells_with_clone_count[order(n_clone_barcode)]

    n_cells_with_clone_count[, perc_and_n_cells := paste0(
        prettyNum(n_cells, big.mark = ","), " (",
        round(100 * n_cells / n_valid_cells, 1),
        "%)")]
}
